#! /bin/sh
### Startup
flameshot       &
sxhkd           &
setxkbmap pl	  &
dunst           &
picom           &
~/.config/polybar/launch.sh &
feh --bg-fill ~/pics/wallpapers/minimalistic/purp.png
export QT_QPA_PLATFORMTHEME=qt5ct

### Desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9 

### Settings
#bspc config border_width        1
bspc config window_gap          9
bspc config top_padding         45
bspc config left_padding        4
bspc config right_padding       4
bspc config bottom_padding      45
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config pointer_modifier    mod1
bspc config pointer_action3     resize_side
bspc config pointer_action3     resize_corner
bspc config pointer_action1     move

### Rules
bspc rule -a kitty              desktop="^1" follow=on state=floating
bspc rule -a discord            desktop="^2" follow=on state=floating
bspc rule -a telegram-desktop   desktop="^2" follow=on state=floating
bspc rule -a nemo                            follow=on state=floating
bspc rule -a spotify            desktop="^3" follow=on
bspc rule -a librewolf          desktop="^4" follow=on
