#! /bin/sh

# A U T O S T A R T

flameshot       &
sxhkd           &
setxkbmap pl	  &
dunst           &
picom           &
~/.config/polybar/launch.sh &
feh --bg-fill /home/hexa/Pictures/wallpapers/minimalistic/city.jpg
export QT_QPA_PLATFORMTHEME=qt5ct

# D E S K T O P S

bspc monitor -d 1 2 3 4 5 6 7 

# W I N D O W S

bspc config border_width        4
bspc config window_gap          9
bspc config top_padding         45
bspc config left_padding        4
bspc config right_padding       4
bspc config bottom_padding      1

bspc config normal_border_color   "#4B4459"
bspc config focused_border_color  "#ffffff"

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true

bspc config pointer_modifier    mod1
bspc config pointer_action3     resize_side
bspc config pointer_action3     resize_corner
bspc config pointer_action1     move

# R U L E S

bspc rule -a kitty              desktop="^1" follow=on
#bspc rule -a Pcmanfm            desktop="^2" follow=on
bspc rule -a discord            desktop="^2" follow=on
bspc rule -a discord-canary     desktop="^2" follow=on
#bspc rule -a steam              desktop="^4" follow=on
#bspc rule -a steamwebhelper     desktop="^4" follow=on
bspc rule -a spotify            desktop="^3" follow=on
bspc rule -a librewolf              desktop="^4" follow=on
bspc rule -a firefox          desktop="^4" follow=on
bspc rule -a brave-browser           desktop="^4" follow=on
